### PR TITLE
create dev-requirements.txt file

### PR DESCRIPTION
**Pull request by Sheila-nk**
- created a `dev-requirements.txt` file with dependencies that will allow GitHub workflows to run tests on push and pull request events

### CODE REVIEW

**Comment by Sheila-nk** [comment]
@GeorgianaElena , do I need to pin the packages to versions here or it's not necessary?

**Review by GeorgianaElena — COMMENTED** [review]
Thanks for opening this @Sheila-nk!

> created a dev-requirements.txt file with dependencies that will allow GitHub workflows to run tests on push and pull request events

Can you please give more details about what you mean by this and how do you plan to use this file in a GitHub workflow? I don't think I understand.

**Comment by minrk** [comment]
dev-requirements.txt was removed in favor of `jupyterhub[test]` in #4223.

**Comment by Sheila-nk** [comment]
> Can you please give more details about what you mean by this and how do you plan to use this file in a GitHub workflow? I don't think I understand.

Yes, sorry I should have given more context. 
I am currently working on setting up GitHub workflows to run tests on push and pull request events.
One of the steps involves [installing python dependencies here](https://github.com/Sheila-nk/pytest-jupyterhub/blob/f3bb4458bd7d83343b73f8a611a47f6a82e98abc/.github/workflows/test.yml#L53) that enable workflows to run the tests which I can do through a requirements.txt file. I am still learning about GitHub workflows so feel free to correct me.

**Comment by GeorgianaElena** [comment]
> One of the steps involves [installing python dependencies here](https://github.com/Sheila-nk/pytest-jupyterhub/blob/f3bb4458bd7d83343b73f8a611a47f6a82e98abc/.github/workflows/test.yml#L53) that enable workflows to run the tests which I can do through a requirements.txt file. I am still learning about GitHub workflows so feel free to correct me.

We currently use  a [hatchling build system](https://hatch.pypa.io/latest/) and all the build requirements and information is stored inside a [`pyproject.toml` file](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/).

And we already list the test dependencies inside this `pyproject.tom`l file under `project.optional_dependencies`:
https://github.com/jupyterhub/pytest-jupyterhub/blob/5a97135c6368b6eb88f0b6029e7f1400584c5fd6/pyproject.toml#L39-L45

Alternatively, [a `requiremetns` file can be used to specify dependecies](https://pip.pypa.io/en/stable/reference/requirements-file-format/#requirements-file-format), but it's not what we're using for this project and there's no reason to add one and use both formats.

Instead of having the test requiremets in two places, we can just rely on the `project.optional_dependencies` in `pyproject.toml` and have a GitHub workflow step that pip - installs them with":
```bash
pip install -e ".[test]"
```

This command installs the project in [editable mode](https://pip.pypa.io/en/stable/topics/local-project-installs/#editable-installs) and installs the packages we listed as requirements for running the tests. You can read more about installing optional dependencies from [here](https://hatch.pypa.io/latest/config/dependency/#features).

Below are two GitHub workflows examples from the `jupyterhub` org examples for installing the pkg and its test dependencies without a requirements file:

- `jupyterhub/jupyterhub`
https://github.com/jupyterhub/jupyterhub/blob/c93832cb33fd00cb7978a0c4428d5af9a69ba968/.github/workflows/test.yml#L144

- `jupyterhub/kubespawner`
https://github.com/jupyterhub/kubespawner/blob/cd4c08d5e175e3b6d58e279c27265e6e95e6197b/.github/workflows/test.yaml#L66-L69

**Comment by Sheila-nk** [comment]
@GeorgianaElena thank you so much for the insight and resources. I have used  `pip install -e ".[test]"`  to install the python dependencies and it works perfectly. The workflows now fail due to the absence of the `tests` directory which I am currently working on.
I think I will close this PR now.

**Comment by GeorgianaElena** [comment]
@Sheila-nk, I found this blog post very intersesting and useful for understanding the current state of the python packaging ecosystem https://pradyunsg.me/blog/2023/01/21/thoughts-on-python-packaging/

**Pull request closed without merging**
