### PR TITLE
pre-commit: bump isort

### PR DESCRIPTION
**Pull request by Sheila-nk**
- Upgrade isort to the most recent version

### CODE REVIEW

**Comment by consideRatio** [comment]
@Sheila-nk yies I'm sorry!!! I merged too quickly! This PR included more than the isort bump.

What happens when I then merged is that https://github.com/jupyterhub/pytest-jupyterhub/pull/28 was closed automatically, as that PR included these other commits already and was considered no longer needed.

**Comment by GeorgianaElena** [comment]
Yeah, I think this branch was based of the one in https://github.com/jupyterhub/pytest-jupyterhub/pull/28.

**Comment by Sheila-nk** [comment]
@consideRatio no problem, the other commits are not supposed to be included in this PR. Allow me to sort that out first.

**Comment by consideRatio** [comment]
Thank you @Sheila-nk, I'm sorry for the trouble!

**Comment by GeorgianaElena** [comment]
@Sheila-nk, @consideRatio, there's no need to revert anything. I was planning to merge #28 as well soon also, so this a good thing. Thank you 🚀 !

@Sheila-nk, let's  leave a small note in the top comment if a PR is based on changes that haven't been merged yet. Or, create branches directly from `main` if changes don't depend on each other. Thank you!

**Comment by Sheila-nk** [comment]
> @Sheila-nk, let's leave a small note in the top comment if a PR is based on changes that haven't been merged yet. Or, create branches directly from main if changes don't depend on each other. Thank you!

@GeorgianaElena Alright, will make sure to do that moving forward. Thank you!
@consideRatio apologies for the confusion!

**Pull request merged**
