### PR TITLE
make all plugin fixtures async

### PR DESCRIPTION
**Pull request by Sheila-nk**
- made all fixtures async so they are all integrated into the event loop
- used awaits to directly call coroutines `initialize` and `start`

Reference: #13

### CODE REVIEW

**Comment by Sheila-nk** [comment]
Related to #30

**Review by GeorgianaElena — CHANGES_REQUESTED** [review]
This is great! Thanks for opening this PR @Sheila-nk ✨ 

[We want to use](https://github.com/jupyterhub/pytest-jupyterhub/blob/8e1356936c986b636c028b004dbaf02b17021431/pyproject.toml#L41) the [`pytest-asyncio` plugin](https://pytest-asyncio.readthedocs.io/en/latest/index.html) to test jupyterhub's components that use the `asyncio` lib. So, in  order for these async fixtures to be handeled by the `pytest-asyncio` plugin, they should be [marked as async](https://pytest-asyncio.readthedocs.io/en/latest/reference/markers.html#pytest-mark-asyncio).

_Note:_ I believe we can take advantage of the [pytest-asyncio auto discovery mode](https://pytest-asyncio.readthedocs.io/en/latest/concepts.html#auto-mode) to mark all coroutines as async.

**Comment by Sheila-nk** [comment]
> This is great! Thanks for opening this PR @Sheila-nk ✨
> 
> [We want to use](https://github.com/jupyterhub/pytest-jupyterhub/blob/8e1356936c986b636c028b004dbaf02b17021431/pyproject.toml#L41) the [`pytest-asyncio` plugin](https://pytest-asyncio.readthedocs.io/en/latest/index.html) to test jupyterhub's components that use the `asyncio` lib. So, in order for these async fixtures to be handeled by the `pytest-asyncio` plugin, they should be [marked as async](https://pytest-asyncio.readthedocs.io/en/latest/reference/markers.html#pytest-mark-asyncio).
> 
> _Note:_ I believe we can take advantage of the [pytest-asyncio auto discovery mode](https://pytest-asyncio.readthedocs.io/en/latest/concepts.html#auto-mode) to mark all coroutines as async.

Since we have enabled auto discovery mode within the [pyproject.toml](https://github.com/jupyterhub/pytest-jupyterhub/blob/8e1356936c986b636c028b004dbaf02b17021431/pyproject.toml#L96) file, won't all the async fixtures be handled by pytest-asyncio? Or is this only specific to tests and not fixtures?

**Review by GeorgianaElena — APPROVED** [review]
Yes, of course 😅 Sorry for not checking before.

Then I believe this is ready for a merge!

**Pull request merged**
