### PR TITLE
Add pre-commit config, flake8 config, enable autoflake

### PR DESCRIPTION
**Pull request by GeorgianaElena**
Per recommendations in https://jupyterhub-python-repo-template.readthedocs.io/en/latest/tests.html#pre-commit-pre-commit-config-yaml-and-pre-commit-ci

### CODE REVIEW

**Review by consideRatio — APPROVED** [review]
Nice LGTM!

I'll leave it to @Sheila-nk to approve/merge, it can be nice to see the kind of autoformatting changes made by pre-commit automatically. In this PR one can see for example new lines between markdown headers and the associated text, and a blank new lines before the end of a file.

I recommend doing `pip install pre-commit` and `pre-commit install --install-hooks` from this git repo after this is merged so that pre-commit helps get things fixed even before things get committed.

If you have something you are about to commit after having setup pre-commit locally, and something was changed by autoformatters you will see those changes as non-staged when using `git status` and the git commit you tried to make was never fully made.

Then what you do is to inspect the changes with `git diff` and do `git add <files>` to accept those changes and then try the `git commit` command again.

**Comment by consideRatio** [comment]
I went ahead and added the `maintenace` label for this to help generation of changelogs with `github-activity`.

**Comment by GeorgianaElena** [comment]
> I'll leave it to @Sheila-nk to approve/merge

@consideRatio, just noting that even though I self-merged without @Sheila-nk's input here, I did it over a video call we had this morning ❤️ 

> I wonder if the defined hooks are fixed for all JuyterHub projects or if there is room for additional hooks when the need arises.

Definitely not fixed @Sheila-nk. They should be rather seen like recommendations and examples of practices that have proven to be useful.

**Comment by Sheila-nk** [comment]
> @consideRatio, just noting that even though I self-merged without @Sheila-nk's input here, I did it over a video call we had this morning ❤️

Yes! The PR looked great and ready to merge!! The approval was given on video chat. Again, great job @GeorgianaElena 👏

**Pull request merged**
